Repository Malaba6/E-Rental, pull requests merged in 2019-07, with the labels that each got.

#1 User should be able to view the landing page UI #167148087
  .DS_Store
  UI/.DS_Store
  UI/css/main.css
  UI/img/Rental-House.jpg
  UI/img/erental-logo.jpg
  UI/img/erental-logo.png
  UI/img/images.txt
  UI/img/search-icon.png
  UI/img/search.jpg
  UI/index.html
Labels: Needs Reviews, WIP

#2 User should be able to view a specific house and flag a house #167155025
  UI/css/modal.css
  UI/css/view_specific_house.css
  UI/html/view_specific_house.html
  UI/img/four.jpg
  UI/img/one.jpg
  UI/img/three.jpg
  UI/js/modal.js
  UI/js/view_specific_house.js
Labels: Finished

#3 User can view all available houses #167154609
  UI/css/main.css
  UI/html/view_all_available_houses.html
  UI/html/view_specific_house.html
  UI/img/house1.jpg
  UI/img/house10.jpg
  UI/img/house11.jpg
  UI/img/house12.jpeg
  UI/img/house2.jpg
  UI/img/house3.jpeg
  UI/img/house4.jpeg
  UI/img/house5.jpeg
  UI/img/house6.jpeg
  UI/img/house7.jpeg
  UI/img/house8.jpeg
  UI/img/house9.jpg
  UI/index.html
Labels: Finished

#5 Landlord can post a house for rent [#167161225]
  UI/css/postHouse.css
  UI/html/postHouse.html
  UI/html/view_all_available_houses.html
  UI/html/view_specific_house.html
  UI/images/architecture-concrete-daylight-2102587.jpg
  UI/index.html
  UI/js/main.js
Labels: Finished

#6 #167148017 built sign-up page
  UI/css/main.css
  UI/css/sign-up-sass.scss
  UI/css/sign-up-style.css
  UI/css/sign-up-style.css.map
  UI/html/sign-up.html
  UI/img/house-for-rent.jpg
  UI/index.html
Labels: Needs Reviews

#7 View posted house ads for rent #167355516
  UI/html/your_ads.html
  UI/index.html
Labels: Finished, Needs Reviews

#10 Set up the server #167395883
  .babelrc
  .eslintrc.js
  app.js
  package-lock.json
  package.json
  server/controller/flagController.js
  server/controller/houseController.js
  server/controller/requestController.js
  server/controller/userController.js
  server/database/bd.js
  server/helper/customize.js
  server/helper/status.js
  server/middleware/authenticate.js
  server/middleware/uploadImage.js
  server/model/flags.js
  server/model/houses.js
  server/model/requests.js
  server/model/users.js
  server/route/routes.js
  server/test/flag.test.js
  server/test/house.test.js
  server/test/request.test.js
  server/test/user.test.js
Labels: Needs Reviews

#11 #167399298 built user registration endpoint
  .eslintrc.js
  app.js
  package-lock.json
  package.json
  server/config/dbConfig.js
  server/controllers/authController.js
  server/controllers/flagController.js
  server/controllers/houseController.js
  server/controllers/requestController.js
  server/helpers/customize.js
  server/helpers/hashPassword.js
  server/helpers/status.js
  server/helpers/token.js
  server/middleware/userValidation.js
  server/models/flags.js
  server/models/houses.js
  server/models/requests.js
  server/models/users.js
  server/route/routes.js
  server/routes/authRoutes.js
  server/test/flag.test.js
  server/test/house.test.js
  server/test/request.test.js
  server/test/user.test.js
  server/tests/dummy.js
  server/tests/flag.test.js
  server/tests/house.test.js
  server/tests/request.test.js
  server/tests/user.test.js
Labels: Finished, Needs Reviews

#16 feat(view house endpoint): User can view a specific house
  server/controllers/houseController.js
  server/middleware/authenticate.js
  server/middleware/houseValidation.js
  server/routes/houseRoutes.js
Labels: Needs Reviews

#17 feat(view all houses endpoint): User can view all available houses for rent
  package.json
  server/controllers/houseController.js
  server/routes/houseRoutes.js
  server/tests/user.test.js
Labels: Needs Reviews

#18 #167396912 solved the conflicts and bugs
  app.js
  server/controllers/houseController.js
  server/middleware/houseValidation.js
  server/routes/authRoutes.js
  server/routes/houseRoutes.js
  server/tests/house.test.js
  server/tests/user.test.js
Labels: Finished, Needs Reviews

#19 User can flag a house as fraudulent #167397090
  app.js
  server/config/dbConfig.js
  server/controllers/flagController.js
  server/middleware/flagValidation.js
  server/models/flags.js
  server/routes/flagRoutes.js
  server/tests/flag.test.js
Labels: Finished, Needs Reviews

#20 #167531651 change error messages in post house
  server/controllers/houseController.js
Labels: Finished, Needs Reviews

#21 [Start #167534750] add test for getting all houses
  server/controllers/houseController.js
  server/tests/house.test.js
Labels: Needs Reviews
